#!/usr/bin/env bash

main(){
    1> >(while read outln; do echo -e "\033[${outfmt:-0}m${outln}\033[0m"; done) \
    2> >(while read errln; do echo -e "\033[${errfmt:-31}m${errln}\033[0m"; done) \
    exec "$@"
    exit $?
}

main "$@"
